### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by hyun99999** [29th-WE-SOPT-iOS-Part/KimHyeonGyu#12]
## 📌  Feature Issue

- imageView 가 tap 되었을 때 상세정보를 가지고 새로운 뷰로 화면전환

## 📝  To-do

- [x] cell 안의 image view 에 tap gesture 등록
- [x] cell 선언시 화면전환 클로저 설정
- [x] imageView, title, subtitle 데이터 전달
